version: '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--reload" ]
    volumes:
      - ./src:/usr/src/shade_route_api/src
