version: '3'

services:
  postgis:
    image: pgrouting/pgrouting:12-3.0-2.6.3
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgis
    environment:
      DB_HOST: postgis
      DB_PORT: 5432
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
    entrypoint: [ "dockerize", "-timeout", "60s", "-wait", "tcp://postgis:5432" ]
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--reload" ]
    volumes:
      - ./src:/usr/src/shade_route_api/src
      - ./bin:/usr/src/shade_route_api/bin
