DO $$
BEGIN
  CREATE ROLE ursci LOGIN PASSWORD 'SECRET_PASSWORD' NOINHERIT VALID UNTIL 'infinity';
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'Role already exists';
END
$$;

GRANT ALL PRIVILEGES ON DATABASE hikage_prod TO ursci;
